import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  homeContainer: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    paddingTop: 40,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerLogo: {
    width: 50,
    height: 50,
    marginRight: 15,
    borderRadius: 25,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  content: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  logo: { width: 150, height: 150, borderRadius: 75, marginBottom: 20 },
  welcomeText: { fontSize: 28, fontWeight: 'bold', textAlign: 'center', marginBottom: 10 },
  sloganText: { fontSize: 18, textAlign: 'center', fontStyle: 'italic' },
  tabBar: {
    flexDirection: 'row',
    height: 70,
    width: Dimensions.get('window').width,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'absolute',
    bottom: 0,
    left: 0,
    elevation: 5,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabText: { fontSize: 12, marginTop: 2 },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 50,
    margin: 10,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchIcon: { marginRight: 10 },
  searchInput: { flex: 1, fontSize: 16 },
  settingsContainer: { flex: 1 },
  section: { paddingHorizontal: 20, marginBottom: 30 },
  sectionTitle: { fontSize: 22, fontWeight: 'bold', marginBottom: 15 },
  optionButton: {
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  optionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  taskItem: {
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taskContent: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  taskDetails: { marginLeft: 10, flex: 1 },
  taskActions: { flexDirection: 'row', gap: 15 },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  notificationModal: {
    width: '85%',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  modalTitle: { fontSize: 22, fontWeight: 'bold', marginLeft: 10 },
  modalSubtitle: { fontSize: 16, marginBottom: 20, textAlign: 'center' },
  actionButtons: { flexDirection: 'row', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
    elevation: 3,
  },
  actionButtonText: { color: '#fff', fontSize: 16, fontWeight: '600', marginLeft: 8 },
  modalContent: { width: '85%', padding: 20, borderRadius: 15, elevation: 5 },
  input: { borderWidth: 1, borderRadius: 5, padding: 10, marginBottom: 10, fontSize: 16 },
  dateButton: { padding: 10, borderRadius: 5, marginBottom: 10, alignItems: 'center' },
  colorLabel: { fontSize: 16, marginBottom: 10 },
  colorPicker: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  colorOption: { width: 30, height: 30, borderRadius: 15 },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 20, gap: 10 },
  productivityContainer: { flex: 1, padding: 20 },
  productivityTitle: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  statsContainer: { padding: 15, borderRadius: 10, backgroundColor: 'rgba(0,0,0,0.05)' },
  stat: { fontSize: 16, marginBottom: 10 },
  recommendation: { fontSize: 14, fontStyle: 'italic', marginTop: 10 },
  fab: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    right: 20,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  noTasksContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    marginTop: 50,
  },
  noTasksText: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  noTasksSubText: {
    fontSize: 18,
    marginBottom: 5,
  },
  noTasksActionText: {
    fontSize: 16,
    fontStyle: 'italic',
  },
});